name: Codacy Analysis CLI

on: ["push"]

jobs:
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        run: python KubeSec-master/fuzz.py