name: Run fuzz.py 

on: "push"

jobs:
  codacy-analysis-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Execute fuzz.py 
        run: python fuzz.py